apiVersion: v1
kind: Service
metadata:
  name: {{ template "rippled.fullname" . }}
  labels:
    app: {{ template "rippled.name" . }}
    chart: {{ template "rippled.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.wsWss }}
      targetPort: {{ .Values.service.port.wsWss }}
      protocol: TCP
      name: ws-wss
  selector:
    app: {{ template "rippled.name" . }}
    release: {{ .Release.Name }}
